{% set version = "2.8.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mongolite
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mongolite_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mongolite/mongolite_{{ version }}.tar.gz
  sha256: 96ff82ae17f423f2f5895f5fe8327604268100a72014dd33c0b566f9773eb042

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-jsonlite >=1.4
    - r-mime
    - r-openssl >=1.0
    - cyrus-sasl
  run:
    - r-base
    - r-jsonlite >=1.4
    - r-mime
    - r-openssl >=1.0
    - cyrus-sasl

test:
  commands:
    - $R -e "library('mongolite')"           # [not win]
    - "\"%R%\" -e \"library('mongolite')\""  # [win]

about:
  home: https://github.com/jeroen/mongolite/ (devel) https://jeroen.github.io/mongolite/ (user manual) http://mongoc.org/ (upstream)
  license: Apache-2.0
  summary: "High-performance MongoDB client based on 'mongo-c-driver' and 'jsonlite'. Includes support for aggregation, indexing, map-reduce, streaming, encryption, enterprise authentication, and GridFS. The online user manual provides an overview  of the available methods in the package: <https://jeroen.github.io/mongolite/>."
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mongolite
# Type: Package
# Title: Fast and Simple 'MongoDB' Client for R
# Description: High-performance MongoDB client based on 'mongo-c-driver' and 'jsonlite'. Includes support for aggregation, indexing, map-reduce, streaming, encryption, enterprise authentication, and GridFS. The online user manual provides an overview  of the available methods in the package: <https://jeroen.github.io/mongolite/>.
# Version: 2.0
# Authors@R: c( person("Jeroen", "Ooms", ,"jeroen@berkeley.edu", role = c("aut", "cre")), person("MongoDB, Inc", role = "cph", comment = "Bundled mongo-c-driver, see AUTHORS file") )
# Imports: jsonlite (>= 1.4), openssl (>= 1.0), mime
# License: Apache License 2.0
# URL: https://github.com/jeroen/mongolite/ (devel) https://jeroen.github.io/mongolite/ (user manual) http://mongoc.org/ (upstream)
# BugReports: https://github.com/jeroen/mongolite/issues
# SystemRequirements: OpenSSL, Cyrus SASL (aka libsasl2)
# RoxygenNote: 6.1.0
# Suggests: spelling, nycflights13, ggplot2
# Language: en-GB
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2018-08-09 18:29:26 UTC; jeroen
# Author: Jeroen Ooms [aut, cre], MongoDB, Inc [cph] (Bundled mongo-c-driver, see AUTHORS file)
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2018-08-09 21:20:03 UTC
