{% set version = "4.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mongolite
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mongolite_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mongolite/mongolite_{{ version }}.tar.gz
  sha256: 09808c1c68ada79b75dc22e617533611ac46f602a8e2194819600ef0d07d2892

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("c") }}            # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-jsonlite >=1.4
    - r-mime
    - r-openssl >=1.0
    - cyrus-sasl
    - zlib
  run:
    - r-base
    - r-jsonlite >=1.4
    - r-mime
    - r-openssl >=1.0
    - cyrus-sasl

test:
  commands:
    - $R -e "library('mongolite')"           # [not win]
    - "\"%R%\" -e \"library('mongolite')\""  # [win]

about:
  home: https://jeroen.r-universe.dev/mongolite
  dev_url: https://github.com/jeroen/mongolite/
  doc_url: https://jeroen.github.io/mongolite/
  license: Apache-2.0
  summary: "High-performance MongoDB client based on 'mongo-c-driver' and 'jsonlite'. Includes support for aggregation, indexing, map-reduce, streaming, encryption, enterprise authentication, and GridFS."
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
