appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: XC8dcQ/Phtl1F4EhgCyih1vmlBGrTqDpa7M3i3BPA1QHJBbtLWW7bo2unID+d0GnwMm1hIq6AfbdP/jRrx7icpP4+/qaVHq3G1/tiXIcTZ5m1SgaiWwGNEkqJetrWugGfH34xQqm6d8mVmbrJOP+QAzm8/PJ56FV1rkfsnCXqP3CMZcfALAcCC2LRd+vyPwCROlj6c7yfLwpzCcV3s2EQDrd9G8GwAOrZFquQ9cii10m/T7qUFEf7R/eb8fJ9OOYy2Lv9Uvk2F5TRYQfJRzqC1f3hVNUYOkZTVksdfQXJGRbO8Pp1KYM/WFZCvvWzL64xOYdyXjZnwUz8GE6bUGjioLXqLQPl/25UXtFEd3SAqSlkmkiAZ3qX8vAXSOGVPQleV4V5p5+ZYbigok0Pa97fTVrVAcQEMCLB8QwAoncwTpLtFdj61AFZqtlbuzH1nG9cqWhLNSNaERNisner50JjVZcJ+RgzolssOwiPKtig/23TXq0rJIN7bg8omI9joQBMNUZPcJiGty0hYSlTkyKpFJSY29HG3S3O9D3yoDBGACe2gavjHhZq3zDCq7zXGPkrgMsfPPYYVwLhIK6qKMsoVIeh+KjkE2T9Gr25d94pGtAVNXffESgcRGPQiN3E715bDI4knGOKs07Lc6ViQwK6Xmhz7oVOO6wfxBF3vvNgGs=}
bot:
  automerge: true
